"""
LLM prose generation client.

D-02 fence: the LLM writes prose only; every hard fact (dates, amounts,
entity_ids) must be injected from the spine via Jinja2 template variables,
never generated by the LLM.

D-06 determinism: prompt-hash caching ensures the same (template, facts)
always produces the same prose output across runs.

Provider selection:
  1. If ANTHROPIC_API_KEY is set: use claude-haiku-4-5 via anthropic SDK
  2. Otherwise: use gpt-4o-mini via openai SDK (OPENAI_API_KEY required)

Security (T-02-04-01): Jinja2 Environment(autoescape=True) escapes any
HTML/script in fact strings before they reach the LLM system prompt.
"""

import hashlib
import json
import os
from pathlib import Path
from typing import Type, TypeVar

from dotenv import load_dotenv
from jinja2 import Environment, FileSystemLoader, select_autoescape
from pydantic import BaseModel

# Load .env from repo root (best-effort; silently skips if absent)
_REPO_ROOT = Path(__file__).parent.parent.parent
load_dotenv(_REPO_ROOT / ".env")

T = TypeVar("T", bound=BaseModel)

_DEFAULT_CACHE_DIR = Path(__file__).parent / "cache"

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_template(template_path: str, facts: dict) -> str:
    """
    Render a Jinja2 template with autoescape enabled (T-02-04-01).

    template_path: absolute or relative path to the .j2 file
    facts: dict of template variables
    """
    template_path_obj = Path(template_path)
    env = Environment(
        loader=FileSystemLoader(str(template_path_obj.parent)),
        autoescape=select_autoescape(["j2", "html", "xml"]),
    )
    template = env.get_template(template_path_obj.name)
    return template.render(**facts)


def _prompt_hash(rendered_prompt: str) -> str:
    """SHA-256 hash of rendered system prompt, first 16 hex chars."""
    return hashlib.sha256(rendered_prompt.encode("utf-8")).hexdigest()[:16]


def _load_cache(cache_dir: Path, prompt_hash: str, output_schema: Type[T]) -> T | None:
    """Return cached model instance if cache hit, else None."""
    cache_file = cache_dir / f"{prompt_hash}.json"
    if cache_file.exists():
        try:
            return output_schema.model_validate_json(cache_file.read_text(encoding="utf-8"))
        except Exception:
            # Corrupt cache — regenerate
            return None
    return None


def _save_cache(cache_dir: Path, prompt_hash: str, result: BaseModel) -> None:
    """Write model JSON to cache file."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_file = cache_dir / f"{prompt_hash}.json"
    cache_file.write_text(result.model_dump_json(), encoding="utf-8")


# ---------------------------------------------------------------------------
# Provider implementations
# ---------------------------------------------------------------------------


def _generate_with_anthropic(
    rendered_system_prompt: str,
    output_schema: Type[T],
) -> T:
    """Call Anthropic claude-haiku-4-5 with structured output."""
    import anthropic  # noqa: PLC0415 — lazy import; not always present

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError(
            "ANTHROPIC_API_KEY is not set. "
            "Set it in .env or the environment before running prose generation."
        )

    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.parse(
        model="claude-haiku-4-5",
        max_tokens=1024,
        temperature=0,
        system=rendered_system_prompt,
        messages=[{"role": "user", "content": "Fill the prose fields."}],
        output_format=output_schema,
    )
    return response.parsed_output  # type: ignore[return-value]


def _generate_with_openai(
    rendered_system_prompt: str,
    output_schema: Type[T],
) -> T:
    """Call OpenAI gpt-4o-mini with structured output via beta.chat.completions.parse."""
    from openai import OpenAI  # noqa: PLC0415 — lazy import

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise ValueError(
            "OPENAI_API_KEY is not set. "
            "Set ANTHROPIC_API_KEY or OPENAI_API_KEY in .env before running prose generation."
        )

    client = OpenAI(api_key=api_key)
    completion = client.beta.chat.completions.parse(
        model="gpt-4o-mini",
        temperature=0,
        max_tokens=1024,
        messages=[
            {"role": "system", "content": rendered_system_prompt},
            {"role": "user", "content": "Fill the prose fields."},
        ],
        response_format=output_schema,
    )
    result = completion.choices[0].message.parsed
    if result is None:
        raise ValueError("OpenAI returned no parsed output")
    return result  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_prose(
    template_path: str,
    facts: dict,
    output_schema: Type[T],
    cache_dir: Path | None = None,
) -> T:
    """
    Generate prose for a document using LLM structured output.

    Args:
        template_path: Path to the Jinja2 .j2 template file.
        facts: Dictionary of spine-derived facts to inject into the template.
               These become read-only context in the LLM system prompt.
        output_schema: Pydantic BaseModel subclass (prose-only fields).
                       The LLM fills only the fields in this schema.
        cache_dir: Directory for prompt-hash response cache. Defaults to
                   data_gen/llm/cache/. Set to None to disable caching.

    Returns:
        Populated instance of output_schema.

    Raises:
        ValueError: If no API key is set, or if the LLM returns invalid output.
        ValidationError: If the LLM output violates the D-02 fence (dollar amounts
                         or dates in prose fields).
    """
    if cache_dir is None:
        cache_dir = _DEFAULT_CACHE_DIR

    # 1. Render Jinja2 template with autoescape (T-02-04-01)
    rendered_system_prompt = _render_template(template_path, facts)

    # 2. Compute prompt hash for caching (D-06)
    phash = _prompt_hash(rendered_system_prompt)

    # 3. Check cache
    if cache_dir is not None:
        cached = _load_cache(cache_dir, phash, output_schema)
        if cached is not None:
            return cached

    # 4. Select provider: Anthropic if key is set, else OpenAI
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
    if anthropic_key:
        result = _generate_with_anthropic(rendered_system_prompt, output_schema)
    else:
        result = _generate_with_openai(rendered_system_prompt, output_schema)

    # 5. Write to cache
    if cache_dir is not None:
        _save_cache(cache_dir, phash, result)

    return result
