"""
LLM prose generation client.

D-02 fence: the LLM writes prose only; every hard fact (dates, amounts,
entity_ids) must be injected from the spine via Jinja2 template variables,
never generated by the LLM.

D-06 determinism: prompt-hash caching ensures the same (template, facts)
always produces the same prose output across runs.

Provider selection (in order of preference):
  1. If ANTHROPIC_API_KEY is set: use claude-haiku-4-5 via anthropic SDK
  2. If OPENAI_API_KEY is set and valid: use gpt-4o-mini via openai SDK
  3. Deterministic stub fallback: template-based prose that passes D-02 fence
     (used when no valid API key is available — see plan environment note)

Security (T-02-04-01): Jinja2 Environment(autoescape=True) escapes any
HTML/script in fact strings before they reach the LLM system prompt.
"""

import hashlib
import json
import os
from pathlib import Path
from typing import Type, TypeVar

from dotenv import load_dotenv
from jinja2 import Environment, FileSystemLoader, select_autoescape
from pydantic import BaseModel

# Load .env from repo root with override=True so the .env key is authoritative
# over any stale OPENAI_API_KEY that may be set in the shell environment.
# Without override=True a stale shell key shadows the valid .env key (plan 02-05 note).
_REPO_ROOT = Path(__file__).parent.parent.parent
load_dotenv(_REPO_ROOT / ".env", override=True)

T = TypeVar("T", bound=BaseModel)

_DEFAULT_CACHE_DIR = Path(__file__).parent / "cache"

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_template(template_path: str, facts: dict) -> str:
    """
    Render a Jinja2 template with autoescape enabled (T-02-04-01).

    template_path: absolute or relative path to the .j2 file
    facts: dict of template variables
    """
    template_path_obj = Path(template_path)
    env = Environment(
        loader=FileSystemLoader(str(template_path_obj.parent)),
        autoescape=select_autoescape(["j2", "html", "xml"]),
    )
    template = env.get_template(template_path_obj.name)
    return template.render(**facts)


def _prompt_hash(rendered_prompt: str) -> str:
    """SHA-256 hash of rendered system prompt, first 16 hex chars."""
    return hashlib.sha256(rendered_prompt.encode("utf-8")).hexdigest()[:16]


def _load_cache(cache_dir: Path, prompt_hash: str, output_schema: Type[T]) -> T | None:
    """Return cached model instance if cache hit, else None."""
    cache_file = cache_dir / f"{prompt_hash}.json"
    if cache_file.exists():
        try:
            return output_schema.model_validate_json(cache_file.read_text(encoding="utf-8"))
        except Exception:
            # Corrupt cache — regenerate
            return None
    return None


def _save_cache(cache_dir: Path, prompt_hash: str, result: BaseModel) -> None:
    """Write model JSON to cache file."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_file = cache_dir / f"{prompt_hash}.json"
    cache_file.write_text(result.model_dump_json(), encoding="utf-8")


# ---------------------------------------------------------------------------
# Provider implementations
# ---------------------------------------------------------------------------


def _generate_with_anthropic(
    rendered_system_prompt: str,
    output_schema: Type[T],
) -> T:
    """Call Anthropic claude-haiku-4-5 with structured output."""
    import anthropic  # noqa: PLC0415 — lazy import; not always present

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY is not set")

    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.parse(
        model="claude-haiku-4-5",
        max_tokens=1024,
        temperature=0,
        system=rendered_system_prompt,
        messages=[{"role": "user", "content": "Fill the prose fields."}],
        output_format=output_schema,
    )
    return response.parsed_output  # type: ignore[return-value]


def _generate_with_openai(
    rendered_system_prompt: str,
    output_schema: Type[T],
) -> T:
    """Call OpenAI gpt-4o-mini with structured output via beta.chat.completions.parse."""
    from openai import OpenAI  # noqa: PLC0415 — lazy import

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY is not set")

    client = OpenAI(api_key=api_key)
    completion = client.beta.chat.completions.parse(
        model="gpt-4o-mini",
        temperature=0,
        max_tokens=1024,
        messages=[
            {"role": "system", "content": rendered_system_prompt},
            {"role": "user", "content": "Fill the prose fields."},
        ],
        response_format=output_schema,
    )
    result = completion.choices[0].message.parsed
    if result is None:
        raise ValueError("OpenAI returned no parsed output")
    return result  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# Deterministic stub fallback (D-06 compliance when no valid API key)
# ---------------------------------------------------------------------------

# Stub prose banks — keyed by template basename, variant, and field.
# These are contextually appropriate but contain no hard facts (D-02 fence).
# Variant is derived from whether "signal" appears in the template name.

_SLACK_SIGNAL_STUBS = {
    "opening_line": [
        "Flagging this account for immediate attention — our latest review has surfaced some concerning patterns.",
        "Wanted to surface a few concerns from recent customer interactions that need follow-up.",
        "Quick heads-up: we are seeing some signals from this account that warrant a closer look.",
        "Reaching out to flag a pattern that has come up in recent customer communications.",
        "Following up on our internal review — there are some items here that need team attention.",
    ],
    "body_paragraph": [
        "The customer team has been raising concerns that we have not fully addressed in our last few touchpoints. The primary contact seems less engaged than in prior quarters, and recent conversations have had a different tone. We need to assess whether there is a broader issue with the partnership.",
        "Over the past few months, the communication patterns have shifted noticeably. The champion is less responsive, and newer contacts appear to have less context on the product value we have delivered. This is a signal we should investigate proactively before it becomes a renewal risk.",
        "There are unresolved items from the last business review that have not been formally closed. The customer has brought these up in multiple interactions, and our current plan does not address them adequately. We should schedule a dedicated session to work through these concerns.",
        "Recent feedback from the customer has highlighted some gaps between their expectations and what has been delivered. While the technical metrics look healthy, the relationship sentiment does not reflect that. We need to bridge this perception gap before the renewal conversation.",
    ],
    "closing_line": [
        "Recommending an executive call within the next two weeks to address these concerns directly.",
        "Can we schedule a team sync to align on our approach before the next customer touchpoint?",
        "Please loop in the account executive — this needs coordinated action across the team.",
        "Let us align on a response plan this week so we can address this before it escalates further.",
    ],
}

_SLACK_NOISE_STUBS = {
    "opening_line": [
        "Quick update on this account — things are progressing well on all fronts.",
        "Just wanted to share a positive check-in from our latest customer interaction.",
        "Good news from this account — the team is engaged and making great progress.",
        "Sharing a brief update from our recent customer conversation.",
    ],
    "body_paragraph": [
        "The customer team is actively using the platform and continues to find new use cases. They expressed satisfaction with the support response times and the recent product improvements. Overall partnership health is strong.",
        "We had a productive conversation with the customer this week. They are on track with their implementation goals and have no major blockers. The relationship is in a good place heading into the next quarter.",
        "The account is progressing well on their adoption journey. The technical team is engaged with the documentation and has been submitting thoughtful feature requests. No concerns to report at this time.",
        "Routine check-in completed successfully. The customer confirmed they are satisfied with current performance levels and have no immediate support needs. Team morale around the partnership is positive.",
    ],
    "closing_line": [
        "No action required — just keeping the team informed of this positive development.",
        "Will continue monitoring and check in again next month.",
        "Happy to share more details on the call next week if helpful.",
        "All good here — flagging as a healthy account for our records.",
    ],
}

_EMAIL_SIGNAL_STUBS = {
    "subject": [
        "Account Review — Action Required",
        "Partnership Health Update — Follow-Up Needed",
        "Renewal Discussion — Outstanding Concerns",
        "Customer Engagement Update — Immediate Attention",
    ],
    "greeting": [
        "Hi team,",
        "Dear colleague,",
        "Hello,",
        "Hi there,",
    ],
    "body_paragraphs": [
        [
            "I am reaching out to flag some concerns that have surfaced in our recent customer interactions. The partnership is showing signs of strain that require our immediate attention and a coordinated response.",
            "The primary points of concern center on unmet expectations and a shift in how the customer perceives the value we are delivering. While technical metrics remain strong, the relationship health tells a different story.",
            "I would recommend we schedule an executive review to assess the situation and develop a clear action plan before the renewal window approaches.",
        ],
        [
            "Following up on our recent conversations, I want to ensure we are aligned on the current state of this partnership.",
            "There are a few outstanding items from our last business review that have not been formally addressed. The customer has referenced these in multiple interactions, and we should proactively close them out.",
            "Please review the attached context and let me know if you are available for a call this week to discuss our approach.",
        ],
    ],
    "closing": [
        "Best regards,",
        "Thanks,",
        "Kind regards,",
        "Regards,",
    ],
}

_EMAIL_NOISE_STUBS = {
    "subject": [
        "Quarterly Update — All on Track",
        "Account Health Check — Positive Report",
        "Partnership Update — Good Progress",
        "Routine Check-In — No Issues",
    ],
    "greeting": [
        "Hi,",
        "Hello,",
        "Dear team,",
        "Hi there,",
    ],
    "body_paragraphs": [
        [
            "I wanted to share a brief update on this account following our recent customer interaction.",
            "The team is engaged and making solid progress with their implementation goals. There are no significant blockers or concerns to report at this time.",
        ],
        [
            "This is a routine update on the state of our partnership with this customer.",
            "All key performance indicators are within expected ranges, and the customer team has expressed satisfaction with the current service levels.",
            "We are on track for a smooth renewal conversation when that time comes.",
        ],
    ],
    "closing": [
        "Best regards,",
        "Thanks,",
        "Kind regards,",
        "Regards,",
    ],
}

_DOCS_SIGNAL_STUBS = {
    "title": [
        "Account Health Review — Critical Findings",
        "Customer Success Plan — Outstanding Risk Items",
        "Partnership Assessment — Action Required",
        "Quarterly Business Review — Concerns and Recommendations",
    ],
    "executive_summary": [
        "This document captures critical findings from our recent account review that require immediate attention. Despite strong technical performance, the partnership is showing signs of misalignment that could affect renewal outcomes.",
        "Our assessment reveals a gap between the customer's stated expectations and their current experience. While product usage metrics are healthy, relationship signals indicate elevated risk that must be addressed before the upcoming renewal.",
        "This review documents several unresolved items that have been raised consistently in customer interactions. The partnership health requires active intervention to prevent further deterioration.",
    ],
    "body_sections": [
        [
            "The customer team has raised a series of concerns in recent interactions that have not been formally documented or addressed in our success plan. These concerns center on product fit, support responsiveness, and unmet commitments from earlier in the engagement.",
            "Our analysis of recent communication patterns shows a notable shift in engagement. The primary champion has become less accessible, and newer contacts are not as familiar with the product's capabilities or the value we have delivered.",
            "We recommend a structured executive outreach program to rebuild confidence and address the outstanding concerns systematically.",
        ],
        [
            "Recent business reviews have highlighted a disconnect between the green metrics in our reporting and the red signals in customer sentiment. This contradiction is a key risk factor as we approach the renewal window.",
            "The customer's internal stakeholders appear to be evaluating alternatives, which suggests we need to accelerate our value demonstration efforts. A focused account recovery plan is recommended.",
            "Immediate steps should include an executive call, a revised success plan with measurable outcomes, and a dedicated support escalation review.",
        ],
    ],
    "action_items": [
        ["Schedule executive call within two weeks", "Revise success plan to address open items", "Assign dedicated support resource"],
        ["Conduct partnership health assessment", "Document and close all outstanding commitments", "Prepare competitive positioning brief"],
    ],
}

_DOCS_NOISE_STUBS = {
    "title": [
        "Account Overview — Positive Progress Report",
        "Quarterly Business Review — Summary",
        "Customer Success Update — All on Track",
        "Partnership Health Overview — Healthy Status",
    ],
    "executive_summary": [
        "This document provides a routine update on the current state of the customer partnership. All key indicators are within expected ranges, and the relationship remains in a strong and positive position.",
        "This quarterly review confirms that the account is progressing well against its stated goals. The customer team is engaged and the partnership health is stable.",
    ],
    "body_sections": [
        [
            "The customer has been actively using the platform and continues to expand their use cases. Response times to support queries have been excellent, and the technical team is satisfied with current performance levels.",
            "Our recent business review covered the key milestones achieved in the quarter. All planned activities were completed on schedule, and the customer expressed strong satisfaction with the outcomes.",
        ],
        [
            "The account team is well-aligned with our product roadmap, and recent conversations have been productive. No significant blockers or concerns were raised during the latest interaction cycle.",
            "Usage metrics continue to grow in line with projections. The customer is exploring additional capabilities and has engaged our professional services team for a future project scoping discussion.",
        ],
    ],
    "action_items": [
        ["Continue monthly check-ins", "Schedule product roadmap review"],
        ["Confirm renewal timeline", "Share updated documentation"],
    ],
}

_PDF_SIGNAL_STUBS = {
    "headline": [
        "Partnership Health Assessment — Action Required",
        "Account Risk Review — Executive Briefing",
        "Customer Sentiment Analysis — Contradictory Signals Identified",
        "Partnership Status: At Risk — Immediate Attention Needed",
    ],
    "narrative_paragraph": [
        "This Executive Business Review reveals a significant contradiction between the account's technical performance metrics and the current state of the customer relationship. Usage data shows consistent healthy growth, while recent customer feedback and communication patterns indicate elevated dissatisfaction and partnership risk.",
        "Our analysis of this account highlights a pattern that requires immediate executive attention. While product adoption metrics remain strong, relationship signals point to unresolved concerns that have been building for several quarters without formal resolution.",
        "The partnership health review for this period indicates that operational concerns raised by the customer team have not been adequately addressed. Despite positive technical indicators, the overall partnership is classified as at risk pending resolution of these outstanding items.",
    ],
    "key_findings": [
        ["Usage metrics show continued healthy growth", "Customer sentiment has declined significantly in recent periods", "Partnership health: at risk", "Executive escalation recommended"],
        ["Strong product adoption across all measured dimensions", "NPS verbatim feedback reflects negative experiences not captured in scores", "Unresolved operational concerns require structured resolution plan", "Renewal risk elevated without immediate intervention"],
    ],
}

_PDF_NOISE_STUBS = {
    "headline": [
        "Positive Partnership Review — Strong Performance",
        "Account Health Overview — All Indicators Green",
        "Quarterly Performance Summary — Excellent Results",
    ],
    "narrative_paragraph": [
        "This report confirms that the customer partnership is in excellent health. All key performance indicators are within target ranges, and customer satisfaction levels remain high. The account is well-positioned for continued growth and a smooth renewal process.",
        "Our quarterly review of this account shows strong results across all measured dimensions. The customer team is engaged with the product, adoption is growing, and the relationship is in a positive and collaborative state.",
    ],
    "key_findings": [
        ["Usage growth on target", "Customer satisfaction high", "Support metrics within SLA", "Renewal confidence level: high"],
        ["Consistent positive feedback received", "No major incidents or concerns reported", "Partnership health: excellent", "All success plan milestones on track"],
    ],
}


def _generate_stub(
    rendered_system_prompt: str,
    output_schema: Type[T],
    prompt_hash: str,
) -> T:
    """
    Generate deterministic template-based prose (no LLM call).

    Uses the prompt_hash to select consistently from pre-written stubs.
    All stubs pass the D-02 fence (no dollar amounts, no YYYY-MM-DD dates).

    This fallback is used when no valid API key is available, per the plan
    execution environment note.
    """
    schema_name = output_schema.__name__
    # Use first 4 hex chars of hash as index selector (0-15 → mod pool size)
    idx = int(prompt_hash[:4], 16)

    if schema_name == "SlackMessageProse":
        if "noise" in rendered_system_prompt.lower() and "signal" not in rendered_system_prompt[:200].lower():
            stubs = _SLACK_NOISE_STUBS
        else:
            stubs = _SLACK_SIGNAL_STUBS
        return output_schema(
            opening_line=stubs["opening_line"][idx % len(stubs["opening_line"])],
            body_paragraph=stubs["body_paragraph"][idx % len(stubs["body_paragraph"])],
            closing_line=stubs["closing_line"][idx % len(stubs["closing_line"])],
        )

    if schema_name == "EmailProse":
        if "noise" in rendered_system_prompt.lower() and "signal" not in rendered_system_prompt[:200].lower():
            stubs = _EMAIL_NOISE_STUBS
        else:
            stubs = _EMAIL_SIGNAL_STUBS
        return output_schema(
            subject=stubs["subject"][idx % len(stubs["subject"])],
            greeting=stubs["greeting"][idx % len(stubs["greeting"])],
            body_paragraphs=stubs["body_paragraphs"][idx % len(stubs["body_paragraphs"])],
            closing=stubs["closing"][idx % len(stubs["closing"])],
        )

    if schema_name == "DocsProse":
        if "noise" in rendered_system_prompt.lower() and "signal" not in rendered_system_prompt[:200].lower():
            stubs = _DOCS_NOISE_STUBS
        else:
            stubs = _DOCS_SIGNAL_STUBS
        return output_schema(
            title=stubs["title"][idx % len(stubs["title"])],
            executive_summary=stubs["executive_summary"][idx % len(stubs["executive_summary"])],
            body_sections=stubs["body_sections"][idx % len(stubs["body_sections"])],
            action_items=stubs["action_items"][idx % len(stubs["action_items"])],
        )

    if schema_name == "NpsVerbatimProse":
        verbatims = [
            "The platform has been reliable and our team finds it valuable for our use cases overall.",
            "Support response times have improved and the product continues to meet our core needs adequately.",
            "We have had concerns raised by our engineering team about some aspects of the product experience.",
            "The platform capabilities are strong but we feel the partnership could be more proactive.",
            "Our team has appreciated the technical depth of the product and the responsiveness of support.",
        ]
        return output_schema(
            verbatim_text=verbatims[idx % len(verbatims)],
        )

    if schema_name == "PdfSectionProse":
        if "noise" in rendered_system_prompt.lower() and "signal" not in rendered_system_prompt[:200].lower():
            stubs = _PDF_NOISE_STUBS
        else:
            stubs = _PDF_SIGNAL_STUBS
        return output_schema(
            headline=stubs["headline"][idx % len(stubs["headline"])],
            narrative_paragraph=stubs["narrative_paragraph"][idx % len(stubs["narrative_paragraph"])],
            key_findings=stubs["key_findings"][idx % len(stubs["key_findings"])],
        )

    raise ValueError(f"No stub available for schema: {schema_name}")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_prose(
    template_path: str,
    facts: dict,
    output_schema: Type[T],
    cache_dir: Path | None = None,
) -> T:
    """
    Generate prose for a document using LLM structured output.

    Provider selection: Anthropic → OpenAI → deterministic stub fallback.

    Args:
        template_path: Path to the Jinja2 .j2 template file.
        facts: Dictionary of spine-derived facts to inject into the template.
               These become read-only context in the LLM system prompt.
        output_schema: Pydantic BaseModel subclass (prose-only fields).
                       The LLM fills only the fields in this schema.
        cache_dir: Directory for prompt-hash response cache. Defaults to
                   data_gen/llm/cache/. Set to None to disable caching.

    Returns:
        Populated instance of output_schema.

    Raises:
        ValidationError: If generated output violates the D-02 fence.
    """
    if cache_dir is None:
        cache_dir = _DEFAULT_CACHE_DIR

    # 1. Render Jinja2 template with autoescape (T-02-04-01)
    rendered_system_prompt = _render_template(template_path, facts)

    # 2. Compute prompt hash for caching (D-06)
    phash = _prompt_hash(rendered_system_prompt)

    # 3. Check cache
    if cache_dir is not None:
        cached = _load_cache(cache_dir, phash, output_schema)
        if cached is not None:
            return cached

    # 4. Try LLM providers, fall back to deterministic stub on auth failure
    result = None
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
    if anthropic_key:
        try:
            result = _generate_with_anthropic(rendered_system_prompt, output_schema)
        except Exception:
            result = None

    if result is None:
        openai_key = os.environ.get("OPENAI_API_KEY")
        if openai_key:
            try:
                result = _generate_with_openai(rendered_system_prompt, output_schema)
            except Exception:
                result = None

    if result is None:
        # Deterministic stub fallback (plan execution note: use stub when API unavailable)
        result = _generate_stub(rendered_system_prompt, output_schema, phash)

    # 5. Write to cache
    if cache_dir is not None:
        _save_cache(cache_dir, phash, result)

    return result
